apiVersion: gameserver.templarfelix.com/v1alpha1
kind: Minecraft
metadata:
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: minecraft-sample
    app.kubernetes.io/part-of: gameserver-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gameserver-operator
  name: minecraft-sample
spec:
  # Container image (default: gameservermanagers/gameserver:minecraft)
  image: gameservermanagers/gameserver:minecraft

  # Persistence configuration
  persistence:
    storageConfig:
      size: 10G
    preserveOnDelete: false

  # Resource requirements - automatically adjusted based on JVM config
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi

  # Ports configuration
  ports:
    - name: minecraft-tcp
      port: 25565
      targetPort: 25565
      protocol: TCP
    - name: minecraft-udp
      port: 25565
      targetPort: 25565
      protocol: UDP

  # Load balancer IP configuration (optional: leave commented for localhost)
  # loadBalancerIP: your-public-ip-address

  # Code server editor password (required for VS Code editor access)
  editorPassword: your-editor-password

  # Node selection configuration (optional)
  # nodeSelector:
  #   disktype: ssd
  #
  # tolerations:
  # - key: "dedicated"
  #   operator: "Equal"
  #   value: "gameserver"
  #   effect: "NoSchedule"
  #
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: "kubernetes.io/arch"
  #           operator: "In"
  #           values: ["amd64"]

  # Minecraft specific configuration
  config:
    # Server type (vanilla, spigot, paper, bukkit, forge, fabric)
    serverType: vanilla

    # Server properties configuration
    serverProperties:
      # Server settings
      serverPort: 25565
      maxPlayers: 20
      motd: "Welcome to My Minecraft Server!"

      # Game settings
      difficulty: normal
      gameMode: survival
      pvp: true
      onlineMode: true

      # Performance settings
      viewDistance: 10
      simulationDistance: 10

      # World settings
      allowNether: true
      allowEnd: true

      # Additional settings
      enforceWhitelist: false
      enableCommandBlocks: false

    # JVM configuration
    jvm:
      maxHeapSize: "2G"
      minHeapSize: "1G"
      extraArgs: "-XX:+UseG1GC"

    # Plugins (only for Spigot, Paper, Bukkit servers)
    plugins: []
      # - name: "EssentialsX"
      #   spigetId: 9089
      #   enable: true
      # - name: "WorldEdit"
      #   spigetId: 1911
      #   enable: true

    # LinuxGSM configuration
    gsm: |
      ## LinuxGSM Configuration for Minecraft
      ### https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/mcserver/_default.cfg

      # Steam credentials (usually not needed for Minecraft)
      steamuser=""
      steampass=""

      # JVM heap settings (automatically adjusted by operator)
      startparameters="-Xms${jvmheap} -Xmx${jvmheap}"

      # Server details
      servicename="mcserver"
      appid="0"