apiVersion: gameserver.templarfelix.com/v1alpha1
kind: Ark
metadata:
  labels:
    app.kubernetes.io/name: ark
    app.kubernetes.io/instance: ark-sample
    app.kubernetes.io/part-of: gameserver-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gameserver-operator
  name: ark-sample
spec:
  # Container image (default: gameservermanagers/gameserver:ark)
  image: gameservermanagers/gameserver:ark

  # Persistence configuration (ARK requires significant storage for world saves)
  persistence:
    storageConfig:
      size: 50G
    preserveOnDelete: false

  # Resource requirements - ARK is resource intensive
  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 2000m
      memory: 8Gi

  # Ports configuration
  ports:
    - name: ark-game-udp
      port: 7777
      targetPort: 7777
      protocol: UDP
    - name: ark-query-udp
      port: 27015
      targetPort: 27015
      protocol: UDP
    - name: ark-rcon-tcp
      port: 27020
      targetPort: 27020
      protocol: TCP

  # Load balancer IP configuration (optional)
  # loadBalancerIP: your-public-ip-address

  # Code server editor password (required for VS Code access)
  editorPassword: your-editor-password

  # Node selection for high performance (recommended for ARK)
  # nodeSelector:
  #   gameserver: "ark"
  # tolerations:
  # - key: "gameserver"
  #   operator: "Equal"
  #   value: "ark"
  #   effect: "NoSchedule"
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: "workload"
  #           operator: "In"
  #           values: ["gaming", "highperformance"]

  # ARK specific configuration
  config:
    # GameUserSettings.ini basic server configuration
    gameUserSettings:
      # Admin password (required for server management)
      adminPassword: "your-admin-password"

      # Server basic information
      serverSettings:
        serverName: "My ARK Kubernetes Server"
        serverDescription: "ARK: Survival Evolved running on Kubernetes"
        maxPlayers: 20
        difficulty: 1.0

        # Gameplay settings
        pvp: true
        allowFriendlyFire: true
        showPlayerMapLocation: true
        showMapLocation: true

        # Performance multipliers
        tamedDinoDamageMultiplier: 1.0
        wildDinoDamageMultiplier: 1.0
        playerDamageMultiplier: 1.0
        structureDamageMultiplier: 1.0
        playerResistance: 1.0
        dinoCountMultiplier: 1.0
        dinoFoodDrainMultiplier: 1.0

        # Server maintenance
        autoSavePeriodMinutes: 15
        disablePvPOption: false

        # Gameplay features
        disableLootCrates: false
        disableStructurePlacementCollision: false

      # Server network configuration
      serverPort: 7777
      rconPort: 27020
      enableRcon: true

      # Map configuration
      serverMap: "TheIsland"  # TheIsland, TheCenter, ScorchedEarth, etc.

      # Advanced settings
      crossplay: true
      modInstaller: false
      mods: ""  # Comma-separated mod IDs: "731604991,924933745"

    # Game.ini advanced configuration
    game:
      # Harvesting rates (how much resources players get)
      harvesting:
        damageMultiplier: 1.0            # General damage multiplier for harvesting
        useSinglePlayerDamage: false      # Use single player harvesting damage

        # Resource-specific harvest quantities
        metalHarvestQuantity: 1.0         # Metal mining multiplier
        woodHarvestQuantity: 1.0          # Wood harvesting multiplier
        stoneHarvestQuantity: 1.0         # Stone harvesting multiplier
        thatchHarvestQuantity: 1.0        # Thatch harvesting multiplier
        flintHarvestQuantity: 1.0         # Flint harvesting multiplier
        crystalHarvestQuantity: 1.0       # Crystal harvesting multiplier
        oilHarvestQuantity: 1.0           # Oil harvesting multiplier
        obsidianHarvestQuantity: 1.0      # Obsidian harvesting multiplier

      # Breeding configuration
      breeding:
        matingIntervalMultiplier: 1.0     # Time between mating attempts (higher = longer intervals)
        eggHatchSpeedScale: 1.0            # How fast eggs hatch (higher = faster)
        babyMaturationSpeedScale: 1.0      # How fast babies grow (higher = faster)
        imprintPeriodMultiplier: 1.0       # Imprinting time multiplier
        singleBabyGestation: false         # One baby per gestation

      # Difficulty and level settings
      difficulty:
        overrideOfficialDifficulty: 0      # Manual difficulty override (0-1)
        difficultyLevel: 0                 # Server difficulty level (0-1)
        maxDifficulty: false               # Whether to use max difficulty
        useSinglePlayerSettings: false     # Use single player harvest rates/damage
        preventSpawningDinosWithoutSaddle: false  # Prevent saddleless dino spawning
        dontUseDifficulty: false           # Don't scale difficulty with time

      # Custom rates
      customRates:
        tamedDinoLevelMultiplier: 0.5      # Tamed dino level scaling (0.5 = levels 0-75)
        wildDinoLevelMultiplier: 0.5       # Wild dino level scaling (0.5 = levels 0-75)
        xpMultiplier: 1.0                  # XP multiplier
        dayCycleSpeedScale: 1.0            # Day/night cycle speed
        randomSupplyCratePoints: false     # Random supply crate locations
        disablePvPAutoBalance: false       # Disable PVP auto-balancing
        disableStructurePlacementCollision: false  # Allow structure placement anywhere

    # LinuxGSM configuration
    gsm: |
      ## LinuxGSM Configuration for ARK
      ### https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/arkserver/_default.cfg

      # Steam credentials (leave empty for public)
      steamuser=""
      steampass=""

      # ARK startup parameters (map name and options)
      startparameters="TheIsland?listen"

      # Server details
      servicename="arkserver"
      appid="376030"