apiVersion: gameserver.templarfelix.com/v1alpha1
kind: ProjectZomboid
metadata:
  labels:
    app.kubernetes.io/name: projectzomboid
    app.kubernetes.io/instance: projectzomboid-sample
    app.kubernetes.io/part-of: gameserver-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gameserver-operator
  name: projectzomboid-sample
spec:
  storage: 10G
  resources:
    requests:
      memory: 8Gi
      cpu: 4
    limits:
      memory: 16Gi
      cpu: 8
  ports:
    - name: port-16261-tcp
      port: 16261
      targetPort: 16261
      protocol: TCP
    - name: port-16262-udp
      port: 16262
      targetPort: 16262
      protocol: UDP

  # Load balancer IP configuration
  # loadBalancerIP: your-public-ip-address

  # Code server editor password
  # editorPassword: your-editor-password

  # Node selection configuration
  # nodeSelector:
  #   disktype: ssd
  #   gpu: "true"
  #
  # tolerations:
  # - key: "dedicated"
  #   operator: "Equal"
  #   value: "gameserver"
  #   effect: "NoSchedule"
  #
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: "kubernetes.io/arch"
  #           operator: "In"
  #           values: ["amd64"]

  config:
    server: |
      ### custom project zomboid server config ###
      ### https://github.com/GameServerManagers/Game-Server-Configs/blob/main/pz/server.ini ###
      [NETWORK]
      DefaultPort=16261
      UDPPort=16262
      ServerBrowserAnnouncedIP=
      UPnP=true
      ServerName=My Project Zomboid Server
      ServerPassword=
      MaxPlayers=16
      RCONPassword=CHANGE_ME
      RCONPort=27015
      Public=true

      [GAME]
      PVP=true
      PauseEmpty=true
      GlobalChat=true
      Open=true
      SpawnPoint=
      SafetySystem=true
      SleepAllowed=true
      Faction=
      Map=

      [SECURITY]
      DiscordEnable=false
      SteamVAC=true
      AntiCheatProtectionType1=true
      AntiCheatProtectionType1ThresholdMultiplier=3.0

      [PERFORMANCE]
      SaveWorldEveryMinutes=15
      PingLimit=200
      BackupsCount=4
      BackupsPeriod=30

      [CHAT]
      VoiceEnable=true
      VoiceMinDistance=5
      VoiceMaxDistance=100
      ChatStreams=

    # linux gsm config
    gsm: |
      ## custom linuxgsm config ###
      ### https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/pzserver/_default.cfg
      steamuser="username"
      steampass='password'
