//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedGameSettings) DeepCopyInto(out *AdvancedGameSettings) {
	*out = *in
	out.Harvesting = in.Harvesting
	out.Breeding = in.Breeding
	out.Difficulty = in.Difficulty
	out.CustomRates = in.CustomRates
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedGameSettings.
func (in *AdvancedGameSettings) DeepCopy() *AdvancedGameSettings {
	if in == nil {
		return nil
	}
	out := new(AdvancedGameSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ark) DeepCopyInto(out *Ark) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ark.
func (in *Ark) DeepCopy() *Ark {
	if in == nil {
		return nil
	}
	out := new(Ark)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Ark) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArkConfig) DeepCopyInto(out *ArkConfig) {
	*out = *in
	in.GameUserSettings.DeepCopyInto(&out.GameUserSettings)
	out.Game = in.Game
	out.GSM = in.GSM
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArkConfig.
func (in *ArkConfig) DeepCopy() *ArkConfig {
	if in == nil {
		return nil
	}
	out := new(ArkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArkGSMConfig) DeepCopyInto(out *ArkGSMConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArkGSMConfig.
func (in *ArkGSMConfig) DeepCopy() *ArkGSMConfig {
	if in == nil {
		return nil
	}
	out := new(ArkGSMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArkGameUserSettings) DeepCopyInto(out *ArkGameUserSettings) {
	*out = *in
	in.ServerSettings.DeepCopyInto(&out.ServerSettings)
	if in.ModInstaller != nil {
		in, out := &in.ModInstaller, &out.ModInstaller
		*out = new(bool)
		**out = **in
	}
	if in.Crossplay != nil {
		in, out := &in.Crossplay, &out.Crossplay
		*out = new(bool)
		**out = **in
	}
	if in.EnableRcon != nil {
		in, out := &in.EnableRcon, &out.EnableRcon
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArkGameUserSettings.
func (in *ArkGameUserSettings) DeepCopy() *ArkGameUserSettings {
	if in == nil {
		return nil
	}
	out := new(ArkGameUserSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArkList) DeepCopyInto(out *ArkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Ark, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArkList.
func (in *ArkList) DeepCopy() *ArkList {
	if in == nil {
		return nil
	}
	out := new(ArkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArkSpec) DeepCopyInto(out *ArkSpec) {
	*out = *in
	in.Base.DeepCopyInto(&out.Base)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArkSpec.
func (in *ArkSpec) DeepCopy() *ArkSpec {
	if in == nil {
		return nil
	}
	out := new(ArkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArkStatus) DeepCopyInto(out *ArkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArkStatus.
func (in *ArkStatus) DeepCopy() *ArkStatus {
	if in == nil {
		return nil
	}
	out := new(ArkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Base) DeepCopyInto(out *Base) {
	*out = *in
	out.Persistence = in.Persistence
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]v1.ServicePort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Base.
func (in *Base) DeepCopy() *Base {
	if in == nil {
		return nil
	}
	out := new(Base)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreedingRates) DeepCopyInto(out *BreedingRates) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreedingRates.
func (in *BreedingRates) DeepCopy() *BreedingRates {
	if in == nil {
		return nil
	}
	out := new(BreedingRates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomRateSettings) DeepCopyInto(out *CustomRateSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomRateSettings.
func (in *CustomRateSettings) DeepCopy() *CustomRateSettings {
	if in == nil {
		return nil
	}
	out := new(CustomRateSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dayz) DeepCopyInto(out *Dayz) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dayz.
func (in *Dayz) DeepCopy() *Dayz {
	if in == nil {
		return nil
	}
	out := new(Dayz)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dayz) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DayzConfig) DeepCopyInto(out *DayzConfig) {
	*out = *in
	out.Game = in.Game
	out.GSM = in.GSM
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DayzConfig.
func (in *DayzConfig) DeepCopy() *DayzConfig {
	if in == nil {
		return nil
	}
	out := new(DayzConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DayzList) DeepCopyInto(out *DayzList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dayz, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DayzList.
func (in *DayzList) DeepCopy() *DayzList {
	if in == nil {
		return nil
	}
	out := new(DayzList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DayzList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DayzSpec) DeepCopyInto(out *DayzSpec) {
	*out = *in
	in.Base.DeepCopyInto(&out.Base)
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DayzSpec.
func (in *DayzSpec) DeepCopy() *DayzSpec {
	if in == nil {
		return nil
	}
	out := new(DayzSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DayzStatus) DeepCopyInto(out *DayzStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DayzStatus.
func (in *DayzStatus) DeepCopy() *DayzStatus {
	if in == nil {
		return nil
	}
	out := new(DayzStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DifficultySettings) DeepCopyInto(out *DifficultySettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DifficultySettings.
func (in *DifficultySettings) DeepCopy() *DifficultySettings {
	if in == nil {
		return nil
	}
	out := new(DifficultySettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameServerConfig) DeepCopyInto(out *GameServerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameServerConfig.
func (in *GameServerConfig) DeepCopy() *GameServerConfig {
	if in == nil {
		return nil
	}
	out := new(GameServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gmod) DeepCopyInto(out *Gmod) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gmod.
func (in *Gmod) DeepCopy() *Gmod {
	if in == nil {
		return nil
	}
	out := new(Gmod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Gmod) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GmodConfig) DeepCopyInto(out *GmodConfig) {
	*out = *in
	in.Game.DeepCopyInto(&out.Game)
	in.GSM.DeepCopyInto(&out.GSM)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GmodConfig.
func (in *GmodConfig) DeepCopy() *GmodConfig {
	if in == nil {
		return nil
	}
	out := new(GmodConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GmodGSMConfig) DeepCopyInto(out *GmodGSMConfig) {
	*out = *in
	if in.Stats != nil {
		in, out := &in.Stats, &out.Stats
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GmodGSMConfig.
func (in *GmodGSMConfig) DeepCopy() *GmodGSMConfig {
	if in == nil {
		return nil
	}
	out := new(GmodGSMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GmodList) DeepCopyInto(out *GmodList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Gmod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GmodList.
func (in *GmodList) DeepCopy() *GmodList {
	if in == nil {
		return nil
	}
	out := new(GmodList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GmodList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GmodServerConfig) DeepCopyInto(out *GmodServerConfig) {
	*out = *in
	if in.AllowCSLua != nil {
		in, out := &in.AllowCSLua, &out.AllowCSLua
		*out = new(bool)
		**out = **in
	}
	if in.FallDamage != nil {
		in, out := &in.FallDamage, &out.FallDamage
		*out = new(bool)
		**out = **in
	}
	if in.AllowVehicles != nil {
		in, out := &in.AllowVehicles, &out.AllowVehicles
		*out = new(bool)
		**out = **in
	}
	if in.AllowNPCs != nil {
		in, out := &in.AllowNPCs, &out.AllowNPCs
		*out = new(bool)
		**out = **in
	}
	if in.AllowWeapons != nil {
		in, out := &in.AllowWeapons, &out.AllowWeapons
		*out = new(bool)
		**out = **in
	}
	if in.AllowProps != nil {
		in, out := &in.AllowProps, &out.AllowProps
		*out = new(bool)
		**out = **in
	}
	if in.AllowEffects != nil {
		in, out := &in.AllowEffects, &out.AllowEffects
		*out = new(bool)
		**out = **in
	}
	if in.AllowRagdolls != nil {
		in, out := &in.AllowRagdolls, &out.AllowRagdolls
		*out = new(bool)
		**out = **in
	}
	if in.M9KWeapons != nil {
		in, out := &in.M9KWeapons, &out.M9KWeapons
		*out = new(bool)
		**out = **in
	}
	if in.Ads != nil {
		in, out := &in.Ads, &out.Ads
		*out = new(bool)
		**out = **in
	}
	if in.DarkRPEconomy != nil {
		in, out := &in.DarkRPEconomy, &out.DarkRPEconomy
		*out = new(bool)
		**out = **in
	}
	if in.MapCycle != nil {
		in, out := &in.MapCycle, &out.MapCycle
		*out = new(bool)
		**out = **in
	}
	if in.VoiceIcon != nil {
		in, out := &in.VoiceIcon, &out.VoiceIcon
		*out = new(bool)
		**out = **in
	}
	if in.Alltalk != nil {
		in, out := &in.Alltalk, &out.Alltalk
		*out = new(bool)
		**out = **in
	}
	if in.PvP != nil {
		in, out := &in.PvP, &out.PvP
		*out = new(bool)
		**out = **in
	}
	if in.LogFile != nil {
		in, out := &in.LogFile, &out.LogFile
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GmodServerConfig.
func (in *GmodServerConfig) DeepCopy() *GmodServerConfig {
	if in == nil {
		return nil
	}
	out := new(GmodServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GmodSpec) DeepCopyInto(out *GmodSpec) {
	*out = *in
	in.Base.DeepCopyInto(&out.Base)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GmodSpec.
func (in *GmodSpec) DeepCopy() *GmodSpec {
	if in == nil {
		return nil
	}
	out := new(GmodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GmodStatus) DeepCopyInto(out *GmodStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GmodStatus.
func (in *GmodStatus) DeepCopy() *GmodStatus {
	if in == nil {
		return nil
	}
	out := new(GmodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarvestingRates) DeepCopyInto(out *HarvestingRates) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarvestingRates.
func (in *HarvestingRates) DeepCopy() *HarvestingRates {
	if in == nil {
		return nil
	}
	out := new(HarvestingRates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JVMConfig) DeepCopyInto(out *JVMConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JVMConfig.
func (in *JVMConfig) DeepCopy() *JVMConfig {
	if in == nil {
		return nil
	}
	out := new(JVMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kf2) DeepCopyInto(out *Kf2) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kf2.
func (in *Kf2) DeepCopy() *Kf2 {
	if in == nil {
		return nil
	}
	out := new(Kf2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kf2) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kf2Config) DeepCopyInto(out *Kf2Config) {
	*out = *in
	in.Game.DeepCopyInto(&out.Game)
	out.GSM = in.GSM
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kf2Config.
func (in *Kf2Config) DeepCopy() *Kf2Config {
	if in == nil {
		return nil
	}
	out := new(Kf2Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kf2GSMConfig) DeepCopyInto(out *Kf2GSMConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kf2GSMConfig.
func (in *Kf2GSMConfig) DeepCopy() *Kf2GSMConfig {
	if in == nil {
		return nil
	}
	out := new(Kf2GSMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kf2GameConfig) DeepCopyInto(out *Kf2GameConfig) {
	*out = *in
	if in.MapCycle != nil {
		in, out := &in.MapCycle, &out.MapCycle
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kf2GameConfig.
func (in *Kf2GameConfig) DeepCopy() *Kf2GameConfig {
	if in == nil {
		return nil
	}
	out := new(Kf2GameConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kf2List) DeepCopyInto(out *Kf2List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kf2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kf2List.
func (in *Kf2List) DeepCopy() *Kf2List {
	if in == nil {
		return nil
	}
	out := new(Kf2List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kf2List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kf2Spec) DeepCopyInto(out *Kf2Spec) {
	*out = *in
	in.Base.DeepCopyInto(&out.Base)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kf2Spec.
func (in *Kf2Spec) DeepCopy() *Kf2Spec {
	if in == nil {
		return nil
	}
	out := new(Kf2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kf2Status) DeepCopyInto(out *Kf2Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kf2Status.
func (in *Kf2Status) DeepCopy() *Kf2Status {
	if in == nil {
		return nil
	}
	out := new(Kf2Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Minecraft) DeepCopyInto(out *Minecraft) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Minecraft.
func (in *Minecraft) DeepCopy() *Minecraft {
	if in == nil {
		return nil
	}
	out := new(Minecraft)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Minecraft) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftConfig) DeepCopyInto(out *MinecraftConfig) {
	*out = *in
	in.ServerProperties.DeepCopyInto(&out.ServerProperties)
	out.JVM = in.JVM
	in.Plugins.DeepCopyInto(&out.Plugins)
	out.GSM = in.GSM
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftConfig.
func (in *MinecraftConfig) DeepCopy() *MinecraftConfig {
	if in == nil {
		return nil
	}
	out := new(MinecraftConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftGSMConfig) DeepCopyInto(out *MinecraftGSMConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftGSMConfig.
func (in *MinecraftGSMConfig) DeepCopy() *MinecraftGSMConfig {
	if in == nil {
		return nil
	}
	out := new(MinecraftGSMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftList) DeepCopyInto(out *MinecraftList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Minecraft, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftList.
func (in *MinecraftList) DeepCopy() *MinecraftList {
	if in == nil {
		return nil
	}
	out := new(MinecraftList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinecraftList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftPlugin) DeepCopyInto(out *MinecraftPlugin) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftPlugin.
func (in *MinecraftPlugin) DeepCopy() *MinecraftPlugin {
	if in == nil {
		return nil
	}
	out := new(MinecraftPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftPlugins) DeepCopyInto(out *MinecraftPlugins) {
	*out = *in
	if in.Install != nil {
		in, out := &in.Install, &out.Install
		*out = make([]MinecraftPlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftPlugins.
func (in *MinecraftPlugins) DeepCopy() *MinecraftPlugins {
	if in == nil {
		return nil
	}
	out := new(MinecraftPlugins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftServerProperties) DeepCopyInto(out *MinecraftServerProperties) {
	*out = *in
	if in.Pvp != nil {
		in, out := &in.Pvp, &out.Pvp
		*out = new(bool)
		**out = **in
	}
	if in.OnlineMode != nil {
		in, out := &in.OnlineMode, &out.OnlineMode
		*out = new(bool)
		**out = **in
	}
	if in.EnableCommandBlocks != nil {
		in, out := &in.EnableCommandBlocks, &out.EnableCommandBlocks
		*out = new(bool)
		**out = **in
	}
	if in.EnforceWhitelist != nil {
		in, out := &in.EnforceWhitelist, &out.EnforceWhitelist
		*out = new(bool)
		**out = **in
	}
	if in.AllowNether != nil {
		in, out := &in.AllowNether, &out.AllowNether
		*out = new(bool)
		**out = **in
	}
	if in.AllowEnd != nil {
		in, out := &in.AllowEnd, &out.AllowEnd
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftServerProperties.
func (in *MinecraftServerProperties) DeepCopy() *MinecraftServerProperties {
	if in == nil {
		return nil
	}
	out := new(MinecraftServerProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftSpec) DeepCopyInto(out *MinecraftSpec) {
	*out = *in
	in.Base.DeepCopyInto(&out.Base)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftSpec.
func (in *MinecraftSpec) DeepCopy() *MinecraftSpec {
	if in == nil {
		return nil
	}
	out := new(MinecraftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftStatus) DeepCopyInto(out *MinecraftStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftStatus.
func (in *MinecraftStatus) DeepCopy() *MinecraftStatus {
	if in == nil {
		return nil
	}
	out := new(MinecraftStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Persistence) DeepCopyInto(out *Persistence) {
	*out = *in
	out.StorageConfig = in.StorageConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Persistence.
func (in *Persistence) DeepCopy() *Persistence {
	if in == nil {
		return nil
	}
	out := new(Persistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectZomboid) DeepCopyInto(out *ProjectZomboid) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectZomboid.
func (in *ProjectZomboid) DeepCopy() *ProjectZomboid {
	if in == nil {
		return nil
	}
	out := new(ProjectZomboid)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectZomboid) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectZomboidConfig) DeepCopyInto(out *ProjectZomboidConfig) {
	*out = *in
	out.Game = in.Game
	out.GSM = in.GSM
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectZomboidConfig.
func (in *ProjectZomboidConfig) DeepCopy() *ProjectZomboidConfig {
	if in == nil {
		return nil
	}
	out := new(ProjectZomboidConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectZomboidList) DeepCopyInto(out *ProjectZomboidList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectZomboid, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectZomboidList.
func (in *ProjectZomboidList) DeepCopy() *ProjectZomboidList {
	if in == nil {
		return nil
	}
	out := new(ProjectZomboidList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectZomboidList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectZomboidServerConfig) DeepCopyInto(out *ProjectZomboidServerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectZomboidServerConfig.
func (in *ProjectZomboidServerConfig) DeepCopy() *ProjectZomboidServerConfig {
	if in == nil {
		return nil
	}
	out := new(ProjectZomboidServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectZomboidSpec) DeepCopyInto(out *ProjectZomboidSpec) {
	*out = *in
	in.Base.DeepCopyInto(&out.Base)
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectZomboidSpec.
func (in *ProjectZomboidSpec) DeepCopy() *ProjectZomboidSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectZomboidSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectZomboidStatus) DeepCopyInto(out *ProjectZomboidStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectZomboidStatus.
func (in *ProjectZomboidStatus) DeepCopy() *ProjectZomboidStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectZomboidStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sdtd) DeepCopyInto(out *Sdtd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sdtd.
func (in *Sdtd) DeepCopy() *Sdtd {
	if in == nil {
		return nil
	}
	out := new(Sdtd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Sdtd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdtdConfig) DeepCopyInto(out *SdtdConfig) {
	*out = *in
	out.Game = in.Game
	out.GSM = in.GSM
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdtdConfig.
func (in *SdtdConfig) DeepCopy() *SdtdConfig {
	if in == nil {
		return nil
	}
	out := new(SdtdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdtdList) DeepCopyInto(out *SdtdList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Sdtd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdtdList.
func (in *SdtdList) DeepCopy() *SdtdList {
	if in == nil {
		return nil
	}
	out := new(SdtdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SdtdList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdtdServerConfig) DeepCopyInto(out *SdtdServerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdtdServerConfig.
func (in *SdtdServerConfig) DeepCopy() *SdtdServerConfig {
	if in == nil {
		return nil
	}
	out := new(SdtdServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdtdSpec) DeepCopyInto(out *SdtdSpec) {
	*out = *in
	in.Base.DeepCopyInto(&out.Base)
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdtdSpec.
func (in *SdtdSpec) DeepCopy() *SdtdSpec {
	if in == nil {
		return nil
	}
	out := new(SdtdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SdtdStatus) DeepCopyInto(out *SdtdStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SdtdStatus.
func (in *SdtdStatus) DeepCopy() *SdtdStatus {
	if in == nil {
		return nil
	}
	out := new(SdtdStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSettings) DeepCopyInto(out *ServerSettings) {
	*out = *in
	if in.ShowPlayerMapLocation != nil {
		in, out := &in.ShowPlayerMapLocation, &out.ShowPlayerMapLocation
		*out = new(bool)
		**out = **in
	}
	if in.PVP != nil {
		in, out := &in.PVP, &out.PVP
		*out = new(bool)
		**out = **in
	}
	if in.AllowFriendlyFire != nil {
		in, out := &in.AllowFriendlyFire, &out.AllowFriendlyFire
		*out = new(bool)
		**out = **in
	}
	if in.DisableLootCrates != nil {
		in, out := &in.DisableLootCrates, &out.DisableLootCrates
		*out = new(bool)
		**out = **in
	}
	if in.ShowMapLocation != nil {
		in, out := &in.ShowMapLocation, &out.ShowMapLocation
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSettings.
func (in *ServerSettings) DeepCopy() *ServerSettings {
	if in == nil {
		return nil
	}
	out := new(ServerSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}
